//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18010.
// 
#pragma warning disable 1591

namespace iRadioDei_WindowsApp.pt.ipp.isep.dei.wvm036 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMusicPreferences_Service", Namespace="http://tempuri.org/")]
    public partial class MusicPreferences_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDadosiRadioDeiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MusicPreferences_Service() {
            this.Url = global::iRadioDei_WindowsApp.Properties.Settings.Default.iRadioDei_WindowsApp_pt_ipp_isep_dei_wvm036_MusicPreferences_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDadosiRadioDeiCompletedEventHandler getDadosiRadioDeiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMusicPreferences_Service/getDadosiRadioDei", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getDadosiRadioDei([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string namePlaylist, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] musicas, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location) {
            this.Invoke("getDadosiRadioDei", new object[] {
                        namePlaylist,
                        musicas,
                        location});
        }
        
        /// <remarks/>
        public void getDadosiRadioDeiAsync(string namePlaylist, string[] musicas, string location) {
            this.getDadosiRadioDeiAsync(namePlaylist, musicas, location, null);
        }
        
        /// <remarks/>
        public void getDadosiRadioDeiAsync(string namePlaylist, string[] musicas, string location, object userState) {
            if ((this.getDadosiRadioDeiOperationCompleted == null)) {
                this.getDadosiRadioDeiOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDadosiRadioDeiOperationCompleted);
            }
            this.InvokeAsync("getDadosiRadioDei", new object[] {
                        namePlaylist,
                        musicas,
                        location}, this.getDadosiRadioDeiOperationCompleted, userState);
        }
        
        private void OngetDadosiRadioDeiOperationCompleted(object arg) {
            if ((this.getDadosiRadioDeiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDadosiRadioDeiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getDadosiRadioDeiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591